# tasks file for Redis-installation
---

- name: Including OS-specific variables
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Ensuring if Redis configuration directory exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: Restart_redis

- name: Install on Ubuntu machine
  include: Redis_ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Install on Redhat machine
  include: Redis_redhat.yml
  when: ansible_os_family == 'RedHat'

